-- Active: 1741454255232@@127.0.0.1@3306@db04_manh
CREATE DATABASE DB04_MANH; 
USE DB04_MANH;

CREATE TABLE CATEGORY 
(
    CATEGORY_ID CHAR(3) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50)
) ;

CREATE TABLE PRODUCT
(
    PRODUCT_ID CHAR(3) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    UNIT_PRICE INT CHECK(UNIT_PRICE >= 0),
    CATEGORY_ID CHAR(3),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) 
);

CREATE TABLE CUSTOMER 
(
    CUSTOMER_ID CHAR(3) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50),
    CUSTOMER_ADDRESS VARCHAR(100)
);

CREATE TABLE ORDERS
(
    ORDER_ID CHAR(3) PRIMARY KEY,
    ORDER_DATE DATE,
    REQUIRED_DATE DATE,
    CUSTOMER_ID CHAR(3),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID), 
    CHECK(ORDER_DATE <= REQUIRED_DATE)
); 

CREATE TABLE ORDER_DETAIL
(
    ORDER_ID CHAR(3),
    PRODUCT_ID CHAR(3),
    ORDER_QUANTITY INT CHECK(ORDER_QUANTITY > 0),
    PRIMARY KEY(ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE DELIVERY
(
    DELIVERY_ID CHAR(3) PRIMARY KEY,
    DELIVERY_DATE DATE,
    ORDER_ID CHAR(3),
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE DELIVERY_DETAIL
(
    DELIVERY_ID CHAR(3),
    PRODUCT_ID CHAR(3),
    DELIVERY_QUANTITY INT CHECK(DELIVERY_QUANTITY > 0),
    PRIMARY KEY(DELIVERY_ID, PRODUCT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (DELIVERY_ID) REFERENCES DELIVERY(DELIVERY_ID)
);